### ISSUE TITLE
Wrong operator name

### ISSUE THREAD

**Issue by ThomasUllrich666** [ibm-cloud-docs/solution-tutorials#104] opened 2022-08-18 21:28 UTC
https://cloud.ibm.com/docs/solution-tutorials?topic=solution-tutorials-openshift-service-mesh&locale=en#openshift-service-mesh-install_istio

wrong operator name:
I think that there is at least a typo within "Step 2: Install Service Mesh - Istio" of the install guide.
The operator names from "Install the Operators" point nr. 4a) and 4c) didn't exist. (and the name Red Hat is printed twice)

a) Red Hat Red Hat OpenShift on IBM Cloud distributed tracing platform
c) Red Hat Red Hat OpenShift on IBM Cloud Service Mesh 

please list the right operator names in this guide. 
Thank you in advance.

**Comment by data-henrik** [comment] 2022-08-19 05:17
Thank you for the feedback. I verified the issue and will make sure it is addressed.

**Comment by data-henrik** [comment] 2022-08-19 14:41
Updates are WIP. The issue is caused by some global update to a text constant which now includes "Red Hat".

**Comment by data-henrik** [comment] 2022-08-23 18:31
The changes are now available. Thanks again for reporting. I will close the issue, but feel free to comment.

**Closed by data-henrik** 2022-08-23 18:31 UTC
Labels: bug
