### ISSUE TITLE
Scalable web Application on OpenShift:  The OpenShift Console Does Not Open Once OpenShift is Successfully Installed

### ISSUE THREAD

**Issue by snyderdb** [ibm-cloud-docs/solution-tutorials#88] opened 2021-09-14 11:42 UTC
Upon successful installation of OpenShift, the console does not open.

**Comment by VidyasagarMSC** [comment] 2021-09-30 05:10
@snyderdb Duplicate of https://github.com/ibm-cloud-docs/solution-tutorials/issues/89?

**Closed** 2022-01-06 19:59 UTC
